name: MacOS forkflow

on:
  push:
    branches:
      - main


jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: create SWIFT file
        run: |
          echo 'print("Hi there")' > hello.swift

      - name: Install dependencies
        run: |
          brew install swiftlint

      - name: Run SWIFT
        run: swiftlint

      - name: Compile
        run: |
          swiftc hello.swift -o hello
          ./hello
          
