name: "run and see the  context"

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:      
      - name: "My step"
        run: echo "Hello! $MY_ACTION $MY_ACTOR"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}

      - name: "Print github.job context"
        run: echo "$JOB_CONTEX"
        env:
          JOB_CONTEX: ${{  github.job }}

      - name: "Print GITHUB_JOB"
        run: echo "$GITHUB_JOB"


         