name: Debug Workflow

on: [push]

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug step
        run: echo "Debug logging is enabled!"