name: "Open new issue"

on: ['push']

jobs:
  open-issue:    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: create issue
        run: |
          gh issue --repo ${{ githib.repository }}
            create  --title "Issue title" --body "Issue body"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}